### ISSUE TITLE
Latest 9.0.12 ver doesn't work on Neo Forge ver 21.0.167

### ISSUE THREAD

**Issue by Faye-Rhayne** [SSKirillSS/Curios#15]
The file states it should work for both 1.21 and 1.21.1 but when updated to latest version on server, it states that it requires 1.21.1 Neoforge and the server will not start. Had to regress back to the 9.0.11 version.

**Comment by SSKirillSS** [comment]
Thanks for the info! I've marked this version as compatible with 1.21.1 only, since it uses new NeoForge features that available only on this version.
