### ISSUE TITLE
maven is down

### ISSUE THREAD

**Issue by screret** [SSKirillSS/Curios#16]
our builds are failing because your maven is down. could you start it back up?

**Comment by SSKirillSS** [comment]
Yea, thanks for the info. Looks like something wrong with Cloudflare. I'll move maven repo to another VPS that will not need redirection in a few hours.

**Comment by SSKirillSS** [comment]
Maven should be migrated now. Based on DNS services update speed, it may be unavailable in your location for some time (up to 48 hours, but in most cases it's close to 1 hour). But looks like it works fine for me now.
