### ISSUE TITLE
[Suggestion] Sync your fork with upstream changes

### ISSUE THREAD

**Issue by Greg-21** [SSKirillSS/Curios#20]
Given that the version 1.21.1 has a good chance of becoming the most popular version in the 1.21.x line among players of modded Minecraft, which is something that the NeoForged Team itself also encourages ([source](https://neoforged.net/news/21.2release/#version-support)), see:

> With Minecraft’s new development policy, minor updates often come with large internal technical changes. These changes are great, and usually benefit modders in the long run. However, they also fragment the community because not all mods are ported or can be ported immediately.
>
> To avoid that fragmentation, **we recommend that modders continue to actively maintain the 1.21.1 version of their mods until the release of Minecraft 1.22**. Of course, we encourage modders who have the time to also try out and release their mods for 1.21.2 too, and we need their feedback to continue improving NeoForge!

I would really appreciate it if my work, originally submitted in TheIllusiveC4#441 to the upstream repository some time ago and recently accepted and merged, was also included in Curios API Continuation for 1.21.1 and later versions.

In such circumstances, may I ask you to sync your fork with the upstream so that my recent update to the Polish translation is also pulled into your repository? According to GitHub, your fork is 13 commits behind (which is a relatively large number, by the way) and includes the commits related to my recent work.

**Comment by SSKirillSS** [comment]
Hi. Should be done now (wherever possible).

**Comment by Greg-21** [comment]
That works for me. Thank you.
