### ISSUE TITLE
[Memory Leak] Revive should not be used anymore.

### ISSUE THREAD

**Issue by pietro-lopes** [SSKirillSS/Curios#22]
This was a bug in original Curios, it was supposed to be a reviveCaps followed by invalidateCaps.
In current versions neither are needed, so you can just remove this line from the code.

https://github.com/SSKirillSS/Curios/blob/6586726c4f724e43197979303c7957d12e824ef3/neoforge/src/main/java/top/theillusivec4/curios/common/event/CuriosEventHandler.java#L274

**Comment by SSKirillSS** [comment]
Hi. Thanks for the info. Should be done now since 9.0.15 release.
