### ISSUE TITLE
[Bug]: Mixin crash in devspace

### ISSUE THREAD

**Issue by AllShamNoWow101** [SSKirillSS/Curios#3]
### Minecraft Version

1.21

### What happened?

Crash occurs when loading client  

### How do you trigger this bug?

Load devspace

### Loader

Neoforge

### Loader Version

neoforge 21.0.91

### Mod Version

curios 9.0.4+1.21

### Relevant Log Outputs

https://pastebin.com/9xAvN9Wu

**Comment by SSKirillSS** [comment]
Weird thing. Works fine for me on [this setup](https://github.com/SSKirillSS/relics/blob/1.21.0/build.gradle).

**Comment by AllShamNoWow101** [comment]
Latest version seemed to fix this issue
