### ISSUE TITLE
[Bug]: Mixin crash in devspace

### ISSUE THREAD

**Issue by yanny7** [SSKirillSS/Curios#5]
### Minecraft Version

1.21

### What happened?

Crash while loading mod in devspace

### How do you trigger this bug?

1. Start devspace with mod

### Loader

NeoForge

### Loader Version

21.0.143

### Mod Version

9.0.5+1.21

### Relevant Log Outputs

https://pastebin.com/QPJXLTpn

**Comment by SSKirillSS** [comment]
Weird. I've just checked it with 21.0.143 NeoForge, and it works fine for me.

This is [my buildscript](https://github.com/SSKirillSS/relics/blob/1.21.0/build.gradle), I've just replaced the NeoForge version with yours.

![image](https://github.com/user-attachments/assets/305a4b83-b04c-4ebb-822f-f9392fc9cf64)

**Comment by yanny7** [comment]
this is my configuration: https://github.com/yanny7/YTech/blob/master/build.gradle
I tried to remove JEI and TOP, but still same crash

**Comment by STS15** [comment]
Can confirm I get the same error in devspace.  It's intermittent and Ive swapped java versions in my mixins.json to 17 then back to 21 and it works for a while then decides to crash again.
https://pastebin.com/f0u2M90p
https://github.com/STS15/Fargos-Talismans/blob/main/build.gradle

**Comment by SSKirillSS** [comment]
Issue should be fixed since 9.0.10 release.

**Comment by yanny7** [comment]
I can confirm that it works now, thanks
