### ISSUE TITLE
[Bug]: 1.21 Neo - BlockDropsEvent causes silk touch to drop experience

### ISSUE THREAD

**Issue by TelepathicGrunt** [SSKirillSS/Curios#6]
### Minecraft Version

1.21

### What happened?

Curios Continuities has a bug where two people reported that Silk Touch drops Experience when mining ores. The modder tracked it down to this curios mod. 

### How do you trigger this bug?

Silk touch mine an ore

### Loader

NeoForge

### Loader Version

doesnt matter

### Mod Version

latest

**Comment by SSKirillSS** [comment]
Thanks for the info! Should be fixed now.
