### ISSUE TITLE
[Bug]: *Not 1.20.6!* 1.21 bug: implumentation of neoforge curios doesnt work

### ISSUE THREAD

**Issue by Playaspect** [SSKirillSS/Curios#7]
### Minecraft Version

1.20.6

### What happened?

cant use anything from curios to make the items, eg. doesn't show the curios implumentation nor anything from curios

### How do you trigger this bug?

1.
2.
3.
...

### Loader

NeoForge

### Loader Version

NeoForge - 21.1.3

### Mod Version

Curios 9.0.5

**Comment by SSKirillSS** [comment]
Hi. It sounds like an issue of your gradle setup, since everything works fine on my curios-based project.

**Comment by Playaspect** [comment]
thanks, ill see if i can fix it and such

**Comment by SSKirillSS** [comment]
Issue should be fixed since 9.0.10 release.
